### ISSUE TITLE
Dependency version conflict with pytest 3.8

### ISSUE THREAD

**Issue by mplovepop** [singer-io/singer-tools#8]
https://github.com/singer-io/singer-tools/blob/240be42b052c6cd25645ef643fdc696ba3fb84db/setup.py#L12

attrs==16.3.0 conflicts with pytest 3.8.0 requirement attrs>=17.4.0

Recommend changing to attrs>=16.3.0 unless there's a compelling reason not to.

**Comment by timvisher** [comment]
Thanks for opening this up. :)

`singer-tools` is not intended to be installed in a `tap`'s virtualenv. Instead, it should be installed into and run from it's own virtualenv to avoid exactly this kind of conflict.

It'd be nice if we could document that in the `README`, though.

Let's change the `Installation` section something to the effect of.

```
singer-tools should be installed into and run from a dedicated virtualenv to avoid version conflicts with the tap it's operating on.

1. Create and activate a virtualenv
2. pip install -e .
3. Run via `<virtualenv>/bin/singer-tools`.

This can be wrapped into a convenience bash script if you desire like:

#!/usr/bin/env bash

mkdir -p ~/.virtualenvs

if ! [[ -f ~/.virtualenvs/singer-tools/bin/activate ]]
then
    python3 -m venv ~/.virtualenvs/singer-tools
    source ~/.virtualenvs/singer-tools/bin/activate
    pip install -U pip setuptools
    pip install -e .
fi

source ~/.virtualenvs/singer-tools/bin/activate

singer-tools "$@"
```

You think you could open a PR to that effect in the near term?
